### ISSUE TITLE
$.prompt undefined in version 6.0.0

### ISSUE THREAD

**Issue by Ionian316** [trentrichardson/jQuery-Impromptu#56]
I have impromptu working fine using version 5.2.5. However, when I upgraded to version 6.0.0, in Firebug I'm getting a "TypeError: $.prompt ... is undefined" error. 

Has anything changed in regards to how to reference Impromptu?
Thanks.

**Comment by trentrichardson** [comment]
For the most part everything should be the same and $.prompt should be defined as well.  A couple older functions were removed, like 

```js
$.prompt.getStateContent()
``` 
Will now need to use 

```js
$.prompt.getState().find('.jqimessage')
```

Are you using getStateContent anywhere?

**Comment by Ionian316** [comment]
Can you look at this fiddle: http://jsfiddle.net/ukoz6Lpn/ ?

In Firefox 36.0.1, it shows the prompt, but if the message is "", then the prompt doesn't show. In IE11 & Chrome, the prompt doesn't show at all, regardless of the message.

**Comment by trentrichardson** [comment]
This works for me, problem was in your fiddle that github will serve the files with the incorrect mime type, so after I updated them to this it worked:
https://rawgit.com/trentrichardson/jQuery-Impromptu/753c2833f62f9c00301dd8b75af03599dc4f2ee8/dist/jquery-impromptu.css
https://rawgit.com/trentrichardson/jQuery-Impromptu/753c2833f62f9c00301dd8b75af03599dc4f2ee8/dist/jquery-impromptu.js

http://jsfiddle.net/ukoz6Lpn/1/

**Comment by trentrichardson** [comment]
In regard to the prompt not showing when blank message is passed this is part of the changes in 6.  You can pass a blank and it won't open the prompt (if it equates to a false, which would be "", undefined, false, etc..)  This is so that you can hold an instance of the prompt, add states, modify, etc. and open when you're ready.  Here is the excerpt from the source:

```js
if(message){
	t.open(message, options);
}
```

So if  you were to follow your call with $.prompt.getApi().open('Hello World'); it would trigger it:

```js
// create the prompt but it will not open yet because 
// there is no message
$.prompt("", {
  title: "Test Prompt",
  buttons: { "OK": true, "Cancel": false }
});

// Ok, now grab the api and tell it to open with the message
// "Hello World"
$.prompt.getApi().open('Hello World');
```

Impromptu can now open several prompts at once, and $.prompt has now become a stack manager for all the prompts.  A call to $.prompt opens a new prompt just like previous versions if there is a message passed.  All other $.prompt.* functions (open, addState, .close, etc) will take action on the prompt last placed on the stack (LIFO).

Hope that clears things up on how Impromptu has changed in version 6

**Comment by Ionian316** [comment]
Thanks so much Trent for the fast and detailed response. That cleared it up. Thanks for creating such a great plugin!
