### ISSUE TITLE
Prompts not always showing in IE11/ME, Graphical Bug

### ISSUE THREAD

**Issue by Rupenbritz** [trentrichardson/jQuery-Impromptu#72]
Hi, we are using impromptu in our web-based tool called Netigate.
We have an issue in IE11/Microsoft Edge where the prompt doesnt display. It exists (because if you hover with mouse you can actually press the buttons inside the prompt for example).

This ONLY happens in IE11 and Microsoft Edge.

![image](https://cloud.githubusercontent.com/assets/9072654/12809606/bc421c62-cb20-11e5-8de2-78befab87fab.png)

The way to display it is either by;
1. Toggling console on and off
2. Scrolling vigiourosly 

![image](https://cloud.githubusercontent.com/assets/9072654/12809623/d3a599ba-cb20-11e5-92e2-de792b2dd7c7.png)

I have no idea why this triggers it too show, it's really strange. 
Have you guys had any similar isue? Any hotfix etc.
All help is really appriciated!

**Comment by trentrichardson** [comment]
Sorry for the delay on this. If you are still having this issue, I suspect opening the console is simply causing the browser to fire a resize event, which Impromptu listens to for repositioning itself.  Are any elements on the page loaded dynamically so that they are loaded after impromptu?  You may also try calling $.prompt.position(); after its loaded to see if that fixes it.. (hack, but at least that is a step toward determining whats happening)

**Comment by Rupenbritz** [comment]
I updated too the latest impromptu and the IE bug seems to have been fixed!

However a since the update a new bug appeared. I will close this topic and open a new one - thx!
